### ISSUE TITLE
Egeria connector does many logins during startup.

### ISSUE THREAD

**Issue by RolfKoolma** [odpi/egeria-connector-hadoop-ecosystem#149]
The startup of the connector is taking a very long time when Atlas is connected to LDAP, and the connector user is not an LDAP user. During startup of the connector it seems to login for every call to Atlas, Atlas then first checks the user against LDAP, doesn't find it and then tries it's own user database.
This takes a lot of extra time. Is it possible to use a session with Atlas so login only happens once?

**Comment by cmgrote** [comment]
I can see that there is an `ATLASSESSIONID` set (via `Set-Cookie` header on a response) when invoking the REST API, which is ultimately what Apache Atlas's client is invoking.  Furthermore, the client class (AtlasBaseClient, from the V2 client we're using extends) provides a `setCookie()` method where this could presumably be passed along.  If set, this would ultimately be used by the `callAPIWithResource()` method, which I suspect is used as the underlying request method ultimately invoked by any method of the client to actually call against Atlas's REST API.

However:
- This `setCookie()` method is not used anywhere by the Atlas code itself (so the Atlas client isn't self-managing the session for us)
- As far as I can see, the API-level response objects that would have the `Set-Cookie` in their header are not ever returned by the client library methods -- so it isn't possible to pull this Cookie off of the response object and use the `setCookie()` method on the client.

So it doesn't appear there's any way to actually use this within the Java client (?)

Finally, I'm not enough of an expert to fully follow the the `webapp/src/main/webapp/WEB-INF/web.xml` configuration file in Atlas's source tree (eg. does this suggests that this cookie is only used for HTTP (non-secure) setup?)

```xml
    <session-config>
        <session-timeout>60</session-timeout>
        <tracking-mode>COOKIE</tracking-mode>
        <cookie-config>
            <name>ATLASSESSIONID</name>
            <http-only>true</http-only>
        </cookie-config>
    </session-config>
```

@RolfKoolma could you please check within your secured environment whether there is even an `ATLASSESSIONID` Set-Cookie header coming back on an API call? eg. in Postman look for something like the following:

<img width="1102" alt="Screenshot 2020-05-06 at 14 30 48" src="https://user-images.githubusercontent.com/5864283/81182928-5fa1be00-8fa6-11ea-99e8-ba4356ae0557.png">
