### ISSUE TITLE
chassis-server requires truststore.p12

### ISSUE THREAD

**Issue by nilmeier** [odpi/egeria-connector-hadoop-ecosystem#213]
When running the egeria-server-chassis-spring.jar file according to the README, the truststore file is required.  If it isn't in the local path, the server won't start.  Including truststore.p12 from the egeria repo fixes this problem, but it is not documented yet.  May be related to odpi/egeria#3705

**Comment by cmgrote** [comment]
Will update docs (README) asap to reflect this (ie. when running the server-chassis from somewhere other than a local build, in the root directory of Egeria core repo where the `truststore.p12` file exists, then we need to ensure there is a `truststore.p12` file present -- eg. copy the one from Egeria core as a placeholder if none other to be used).
