### ISSUE TITLE
Create/update logic and homeId blockers

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria-connector-hadoop-ecosystem#4]
Exploring the Atlas API to create/update an entity, it seems that a self-defined GUID cannot be used (putting a GUID into the request body forces Atlas to attempt an `update`, which then immediately fails as the GUID provided does not yet exist).

Furthermore, even when leaving the GUID off but including a `homeId`, the `homeId` is not stored and entities are still fully mutable (ie. via the UI).

These seem to be fundamental blockers to achieving anything other than a purely read-only connector for Apache Atlas...

**Comment by cmgrote** [comment]
Actually, this was specifically for a glossary and a category...  Maybe the Glossary API must explicitly be used for these particular entities?

**Comment by cmgrote** [comment]
... or not -- doesn't seem that `homeId` even exists on the Glossary API objects / payloads.

**Comment by cmgrote** [comment]
Clarification: above points mean that Atlas cannot currently handle _reference copies_; however, it would likely still be capable of handling master (Atlas-homed) metadata -- with the slight caveat of #3 meaning that fully master metadata support could not (yet) extend to glossary-related entities.

Open question is whether there would be demand for homing metadata in Atlas via the Egeria APIs rather than via Atlas UIs / APIs directly -- otherwise there may be little benefit to extending to cover only master metadata (and still lacking reference copies).

**Comment by bolkedebruin** [comment]
@cmgrote This is addressed in https://issues.apache.org/jira/browse/ATLAS-3755 with a patch available. Would be great if you could test it. Note that it is now a polict item whether someone can create/update system attributes like `homeId`.

Glossary/Category API has not been adjusted yet
