### ISSUE TITLE
Not possible to search for certain strings

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria-connector-hadoop-ecosystem#67]
Searching for certain strings (best guess is those that contain regex-meaningful characters?) does not appear to be possible in Atlas: neither using the `query` / full-text search option, nor the property-specific basic search option.

For example, searching against `qualifiedName` using a contains search with each of the following values all fail to return any results, despite such a result existing in Atlas:

- `est_hive_table1.nam`
- `est_hive_table1\.nam`
- `"est_hive_table1.nam"`
- `"est_hive_table1\.nam"`

The implication of this is that the Egeria Conformance Test Suite (CTS) cannot be passed as certain search scenarios cannot be supported.

**Comment by cmgrote** [comment]
Please see Apache Atlas JIRA: https://issues.apache.org/jira/browse/ATLAS-3574

**Comment by fpompermaier** [comment]
Why this issue is marked as wontfix?

**Comment by cmgrote** [comment]
Hi @fpompermaier -- per the linked Atlas JIRA, this appears to be a limitation in Atlas itself.  There isn't any work we can do to support it in this connector (other than implementing what is likely to be a very poorly performing workaround) until it is resolved in Atlas itself, and therefore it won't be worked on (fixed) in the connector until there is a resolution on the Atlas side.

**Comment by fpompermaier** [comment]
Maybe it could worth to label it as waiting_for_external_fix instead of wontfix.. usually wontfix is used to close the issue to because the isse won't be fixed at all..
